# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
enable_free_tier: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  review_details: false
  poem: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - "development"
  path_filters:
    - "!dist/**"
    - "!storybook-static/**"
    - "!node_modules/**"
chat:
  auto_reply: true
